### PR TITLE
feat: apply theme to preview

### PR DESCRIPTION
**Pull request by btea**

### CODE REVIEW

**Comment by pdanpdan** [comment]
I think it should also change `color` - now the playground is black on dark grey by default in dark mode: https://repl-vuejs.vercel.app/

**Comment by btea** [comment]
@pdanpdan Do you mean to change the color of `h1` tag?

**Comment by pdanpdan** [comment]
More like define the default color scheme for the playground iframe when dark - now the default expects a like background.

**Comment by btea** [comment]
Maybe we can apply the variables here to `srcdoc.html`.
https://github.com/vuejs/repl/blob/7ae106129274f13393808000fd25995d919ae0bd/src/Repl.vue#L136-L143

**Comment by pdanpdan** [comment]
AFAIK you cannot style iframe from outside. So themes for light/dark should be defined for the default example.

**Comment by btea** [comment]
Yeah, so I mean add the above variables here.
https://github.com/vuejs/repl/blob/7ae106129274f13393808000fd25995d919ae0bd/src/output/srcdoc.html#L5-L8

**Comment by pdanpdan** [comment]
I would simply go by defining `color: white` for `html.dark`

**Comment by btea** [comment]
This is indeed simpler.  Are you willing to create a PR to modify it?

**Pull request merged**
